name: Add comment to PR example
on:
  push:
     branches: [ main, 'rbus-**' ]
  pull_request:
     branches: [ main, 'rbus-**' ]
jobs:
  add-comment-to-pr:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set variable_example
        run: echo "variable_example=thomasthornton.cloud" >> $GITHUB_ENV
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: 'rosemarybennyy',
              issue_number: 1,
              repo: 'rbus',
              body: 'rose.cloud'
            })
