name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y  gcc g++ gcov lcov genhtml c++filt gcovr

    - name: Set coverage flags
      run: |
        export COVERAGE_COMPILER_FLAGS="-g -fprofile-arcs -ftest-coverage"
        export CMAKE_Fortran_FLAGS_COVERAGE=${COVERAGE_COMPILER_FLAGS}
        export CMAKE_CXX_FLAGS_COVERAGE=${COVERAGE_COMPILER_FLAGS}
        export CMAKE_C_FLAGS_COVERAGE=${COVERAGE_COMPILER_FLAGS}
        export CMAKE_EXE_LINKER_FLAGS_COVERAGE=""
        export CMAKE_SHARED_LINKER_FLAGS_COVERAGE=""

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Coverage ..
        make

    - name: Run tests
      run: |
        cd build
        ./src/rtmessage/rtrouted
        ./src/session_manager/rbus_session_mgr daemon
        ./unittests/rbus_gtest.bin
        pkill -15 rbus_session_mgr
        ./src/rtmessage/rtrouted_diag shutdown
        rm -rf /tmp/rtrouted*

    - name: Generate lcov coverage report
      run: |
        cd build
        lcov --gcov-tool gcov --directory . --zerocounters
        lcov --gcov-tool gcov --capture --initial --directory . --output-file coverage.base
        lcov --gcov-tool gcov --capture --directory . --output-file coverage.capture
        lcov --gcov-tool gcov -a coverage.base -a coverage.capture --output-file coverage.total
        lcov --gcov-tool gcov --remove coverage.total 'src/dir1/*' 'src/dir2/*' --output-file coverage.info
        genhtml coverage.info --output-directory coverage_report

    - name: Generate gcovr XML coverage report
      run: |
        cd build
        gcovr --xml -r .. -e 'src/dir1/*' -e 'src/dir2/*' --object-directory=. -o coverage.xml

    - name: Generate gcovr HTML coverage report
      run: |
        cd build
        mkdir -p coverage_html
        gcovr --html --html-details -r .. -e 'src/dir1/*' -e 'src/dir2/*' --object-directory=. -o coverage_html/index.html

    - name: Show lcov info report location
      run: echo "Lcov code coverage info report saved in build/coverage.info."

    - name: Show Cobertura XML report location
      run: echo "Cobertura code coverage report saved in build/coverage.xml."

    - name: Show HTML report location
      run: echo "Open build/coverage_html/index.html in your browser to view the coverage report."

    - name: Upload coverage reports
      uses: actions/upload-artifact@v2
      with:
        name: coverage-reports
        path: build/coverage_report,build/coverage.xml,build/coverage_html
