name: Example Workflow
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          echo "MY_VARIABLE=HelloWorld" >> $GITHUB_ENV


  
