name: Example Workflow
on: 
  push:
     branches: [ main, 'rbus-**' ,rbus-codecoverage ]
  pull_request:
     branches: [ main, 'rbus-**', rbus-codecoverage ]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install packages
        run: >
          sudo apt update && sudo apt install -y libcurl4-openssl-dev libgtest-dev lcov gcovr libev-dev valgrind   
      - name: Enable permission to script 
        run: |
          echo $PWD
          chmod a+x test.sh
          echo "ROSE"
          cat test.sh
      - name: Set Environment variables
        run:  |
         echo "MY_VARIABLE=${{github.workspace}}/install/usr/bin/" >$GITHUB_ENV
         ls -lt =${{github.workspace}}/install/usr/bin/
         ls -lt ${
         ls -lt $MY_VARIABLE
      - name: Run shell script
        run:  |
         ./test.sh
        env:
          MY_VARIABLE: ${{env.MY_VARIABLE}} 
         
         
          
      #- name: Run Shell Script
        #run: ./test.sh
        #env:
          #MY_VARIABLE: HelloWorld



  
