name: Example Workflow
on: 
  push:
     branches: [ main, 'rbus-**' ,rbus-codecoverage ]
  pull_request:
     branches: [ main, 'rbus-**', rbus-codecoverage ]
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Enable permission to script 
        run: |
          chmod a+x check-memory.sh
          echo "ROSE"
      #- name: Run Shell Script
        #run: ./check-memory.sh
        #env:
          #MY_VARIABLE: HelloWorld



  
