name: Example Workflow
on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Shell Script
        run: ./check-memory.sh
        env:
          MY_VARIABLE: HelloWorld
